version: 2.1
jobs:
  build:
    docker:
      - image: conanio/clang7
    steps:
      - checkout
      - run:
          command: |
            conan remote add conan-mpusz https://api.bintray.com/conan/mpusz/conan-mpusz
            ./build.sh
