version: 2.1
jobs:
  build:
    docker:
      - image: conanio/clang7:1.15.0
    working_directory: ~/project/Petrichor
    steps:
      - checkout
      - run:
          command: |
            cmake --version
            sudo apt-get install software-properties-common
            sudo add-apt-repository ppa:george-edison55/cmake-3.x
            sudo apt update
            sudo apt install cmake            
            cmake --version
            wget -O ../tbb https://github.com/intel/tbb/releases/download/2019_U8/tbb2019_20190605oss_lin.tgz
            tar -xzvf ../tbb -C ../
            mv ../tbb2019_20190605oss ../tbb-linux
            sudo apt install -y iwyu
            git submodule sync
            git submodule update --init
            bash build.sh
