version: 2.1
jobs:
  build:
    docker:
      - image: conanio/clang7:1.15.0
    working_directory: ~/project/Petrichor
    steps:
      - checkout
      - run:
          command: |
            git submodule sync
            git submodule update --init
            conan remote add conan-mpusz https://api.bintray.com/conan/mpusz/conan-mpusz
            bash build.sh
