version: 2.1
jobs:
  build:
    docker:
      - image: conanio/clang7:1.15.0
    working_directory: ~/project/Petrichor
    steps:
      - checkout
      - run:
          command: |
            cmake --version
            wget -O ../cmake-inst.sh https://github.com/Kitware/CMake/releases/download/v3.15.3/cmake-3.15.3-Linux-x86_64.sh
            sudo mkdir /opt/cmake
            sudo bash ../cmake-inst.sh --prefix=/opt/cmake
            sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
            cmake --version
            wget -O ../tbb https://github.com/intel/tbb/releases/download/2019_U8/tbb2019_20190605oss_lin.tgz
            tar -xzvf ../tbb -C ../
            mv ../tbb2019_20190605oss ../tbb-linux
            sudo apt update
            sudo apt install -y iwyu
            git submodule sync
            git submodule update --init
            bash build.sh
