version: 2.1
jobs:
  build:
    docker:
      - image: conanio/clang7:1.15.0
    working_directory: ~/project/Petrichor
    steps:
      - checkout
      - run:
          command: |
            wget -O ../tbb https://github.com/intel/tbb/releases/download/2019_U8/tbb2019_20190605oss_lin.tgz
            tar -xzvf ../tbb
            mv ../tbb2019_20190605oss ../tbb-linux
            sudo apt update && sudo apt install -y iwyu
            git submodule sync
            git submodule update --init
            bash build.sh
